### Login
POST http://localhost:8080/auth/login
Content-Type: application/json
Authorization: Bearer testUser


### Logout
DELETE http://localhost:8080/auth/logout
Content-Type: application/json
Cookie: idToken=testUser; Path=/; Secure; HttpOnly


### get logs
GET http://localhost:8080/logs
Content-Type: application/json
Cookie: idToken=testUser; Path=/; Secure; HttpOnly
