## create log

POST http://localhost:8080/logs
Content-Type: application/json;charset=UTF-8
Cookie: idToken=testUser; Path=/; Secure; HttpOnly

{
  "date": "2022-02-21T01:03:01.94",
  "diveType": "FREE",
  "enterTime": "2022-02-21T01:03:01.94",
  "leaveTime": "2022-02-21T01:03:01.94",
  "sight": 5,
  "maxDepth": 30,
  "temperature": 10,
  "maxOxygen": 200,
  "minOxygen": 50,
  "location": "경상남도",
  "content": "니모 봤음~~~",
  "longitude": 12.345666,
  "latitude":12.345666
}

### get logs
GET http://localhost:8080/logs?diveType=FREE&location=경상남도&startDate=2022-01-01&endDate=2022-11-01&startDepth=0&endDepth=100&startOxygen=0&endOxygen=100&startSight=0&endSight=100&minTemperature=0&maxTemperature=100&minDepth=0&maxDepth=30&keyword=abc
Cookie: idToken=testUser; Path=/; Secure; HttpOnly

### get log
GET http://localhost:8080/logs/11
Cookie: idToken=testUser; Path=/; Secure; HttpOnly

### delete log
DELETE http://localhost:8080/logs/1
Cookie: idToken=testUser; Path=/; Secure; HttpOnly

### update log
PUT http://localhost:8080/logs/11
Content-Type: application/json;charset=UTF-8
Cookie: idToken=testUser; Path=/; Secure; HttpOnly

{
  "sight": 5,
  "maxDepth": 20,
  "location": "경상북도",
  "content": "니모 봤음~~~",
  "longitude": 12.345666,
  "latitude":12.345666
}
### update log favorite
PUT http://localhost:8080/logs/11/favorite
Content-Type: application/json;charset=UTF-8
Cookie: idToken=testUser; Path=/; Secure; HttpOnly

### add log image
POST http://localhost:8080/logs/3/images
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Cookie: idToken=testUser; Path=/; Secure; HttpOnly

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="test.png"
Content-Type: image/png

< ./test.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### get log images
GET http://localhost:8080/logs/3/images/0
Cookie: idToken=testUser; Path=/; Secure; HttpOnly


### delete log image
DELETE http://localhost:8080/logs/3/images/0
Cookie: idToken=testUser; Path=/; Secure; HttpOnly

